version: '3.8'
services:
  web:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.prod # Use Dockerfile.prod for production
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: f6b6eee9a6c6ce5a182b49c0ef1adde66b5b410f75ec3cbfa10c81167dc0c983195e86920ee2bed9aa1bd2dbe9b750eff8d20d56c5c659e59955c9f391f29eb2
      MASTER_KEY: 6709e60de7c88767004473d14f4e1285
  db:
    image: postgres:13 # Use the desired PostgreSQL version
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: restaurant_menu_app_dev_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB_TEST: restaurant_menu_app_test_db
      POSTGRES_DB_PROD: restaurant_menu_app_prod_db

volumes:
  postgres-data:
