version: '3.8'
services:
  web:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile # Use Dockerfile for development
    volumes:
      - .:/app
    ports:
      - "80:3000" # Exposing the app on port 80 to the outside, mapping to the internal port 3000
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: rails jobs:work
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      RAILS_ENV: development

  db:
    image: postgres:13 # Use the desired PostgreSQL version
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: restaurant_menu_app_dev_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB_TEST: restaurant_menu_app_test_db
      POSTGRES_DB_PROD: restaurant_menu_app_prod_db

volumes:
  postgres-data:
