version: '3.8'

services:
  web:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - .:/app
    ports:
      - "80:4000" # Exposing the app on port 80 to the outside, mapping to the internal port 3000
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}

  worker:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bundle exec rake jobs:work
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}

  db:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: restaurant_menu_app_prod_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret

volumes:
  postgres-data:
