version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev # Use Dockerfile.dev for development
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
  db:
    image: postgres:13 # Use the desired PostgreSQL version
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: restaurant_menu_app_dev_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB_TEST: restaurant_menu_app_test_db
      POSTGRES_DB_PROD: restaurant_menu_app_prod_db

volumes:
  postgres-data:
